stages:
  - execute_pipeline

pipeline_execution:
  stage: execute_pipeline
  image: gitlab-runner-image/tag:latest
  script:
    - curl -X POST -F token=$TOKEN -F ref=$REF "variables[S3_Upload]=$variable"  https://gitlab.com/api/v4/projects/10098/trigger/pipeline 
